package retina.chat.client;

/*
 * PreferencesWindow.java
 *
 * Created on April 2, 2005, 5:20 PM
 *
 * To do list:
 * modify ChatWindow constructor to create PreferencesWindow and Preferences member variables
     with default values for Preferences
 * add getPreferences method to ChatWindow
 * modify ChatWindow to include color and size in the font for displayed text
     in appendChatMessageToChatPanel:
        String size = "4";
        if (preferences.getSize().equals(Preferences.SMALL)) size = "-1";
        else if (preferences.getSize().equals(Preferences.LARGE)) size = "+1";
        else if (preferences.getSize().equals(Preferences.EXTRA_LARGE)) size = "+2";
        appendTextToChatPanel("<font size=\"" + size + "\" color=" + preferences.getColor() + "><b>" + username + ":</b> " + message + "</font>");
 * add a button (WHERE??) to show the PreferencesWindow
 */


public class PreferencesWindow extends javax.swing.JFrame
{
    ChatWindow chatWindow;

    /** Creates new form PreferencesWindow */
    public PreferencesWindow(ChatWindow chatWindow)
    {
        this.chatWindow = chatWindow;
        initComponents();
        initialize();
        setLocationRelativeTo(chatWindow);
        setTitle("Lederhosen 2.0: " + chatWindow.getGroupname() + " Preferences");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents()//GEN-BEGIN:initComponents
    {
        jPanel1 = new javax.swing.JPanel();
        colorLabel = new javax.swing.JLabel();
        colorBox = new javax.swing.JComboBox();
        sizeLabel = new javax.swing.JLabel();
        sizeBox = new javax.swing.JComboBox();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setTitle("Lederhosen 2.0 Chat Window Preferences");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                exitForm(evt);
            }
        });

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 20));

        jPanel1.setMaximumSize(new java.awt.Dimension(350, 100));
        jPanel1.setMinimumSize(new java.awt.Dimension(350, 100));
        jPanel1.setPreferredSize(new java.awt.Dimension(350, 100));
        colorLabel.setText("Color:");
        jPanel1.add(colorLabel);

        colorBox.setMaximumSize(new java.awt.Dimension(80, 19));
        colorBox.setMinimumSize(new java.awt.Dimension(80, 19));
        colorBox.setPreferredSize(new java.awt.Dimension(80, 19));
        colorBox.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                colorBoxHandler(evt);
            }
        });

        jPanel1.add(colorBox);

        sizeLabel.setText("Font Size:");
        jPanel1.add(sizeLabel);

        sizeBox.setMaximumSize(new java.awt.Dimension(80, 19));
        sizeBox.setMinimumSize(new java.awt.Dimension(80, 19));
        sizeBox.setPreferredSize(new java.awt.Dimension(80, 19));
        sizeBox.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                sizeBoxHandler(evt);
            }
        });

        jPanel1.add(sizeBox);

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                handleOkButton(evt);
            }
        });

        jPanel1.add(okButton);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                handleCancelButton(evt);
            }
        });

        jPanel1.add(cancelButton);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Please select a color and font size.");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1, java.awt.BorderLayout.NORTH);

        pack();
    }//GEN-END:initComponents

    private void handleCancelButton(java.awt.event.ActionEvent evt)//GEN-FIRST:event_handleCancelButton
    {//GEN-HEADEREND:event_handleCancelButton
        setVisible(false);
    }//GEN-LAST:event_handleCancelButton

    private void handleOkButton(java.awt.event.ActionEvent evt)//GEN-FIRST:event_handleOkButton
    {//GEN-HEADEREND:event_handleOkButton
        chatWindow.getPreferences().setColor((String)colorBox.getSelectedItem());
        chatWindow.getPreferences().setSize((String)sizeBox.getSelectedItem());
        setVisible(false);
    }//GEN-LAST:event_handleOkButton

    private void sizeBoxHandler(java.awt.event.ActionEvent evt)//GEN-FIRST:event_sizeBoxHandler
    {//GEN-HEADEREND:event_sizeBoxHandler
    }//GEN-LAST:event_sizeBoxHandler

    private void colorBoxHandler(java.awt.event.ActionEvent evt)//GEN-FIRST:event_colorBoxHandler
    {//GEN-HEADEREND:event_colorBoxHandler
    }//GEN-LAST:event_colorBoxHandler

    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt)//GEN-FIRST:event_exitForm
    {
        setVisible(false);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments

    public static void main(String args[])
    {
        new PreferencesWindow().show();
        //new PreferencesWindow().setVisible(true);
    }
     **/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox colorBox;
    private javax.swing.JLabel colorLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton okButton;
    private javax.swing.JComboBox sizeBox;
    private javax.swing.JLabel sizeLabel;
    // End of variables declaration//GEN-END:variables

    private void initialize()
    {
        colorBox.addItem(Preferences.BLACK);
        colorBox.addItem(Preferences.BLUE);
        colorBox.addItem(Preferences.GREEN);
        colorBox.addItem(Preferences.RED);

        sizeBox.addItem(Preferences.SMALL);
        sizeBox.addItem(Preferences.MEDIUM);
        sizeBox.addItem(Preferences.LARGE);
        sizeBox.addItem(Preferences.EXTRA_LARGE);
    }

    public void show()
    {
        colorBox.setSelectedItem(chatWindow.getPreferences().getColor());
        sizeBox.setSelectedItem(chatWindow.getPreferences().getSize());
        super.show();
    }

    public void setVisible(boolean shouldSetVisible)
    {
        if (shouldSetVisible)
        {
            colorBox.setSelectedItem(chatWindow.getPreferences().getColor());
            sizeBox.setSelectedItem(chatWindow.getPreferences().getSize());
        }
        super.setVisible(shouldSetVisible);
    }


}
